import Foundation

struct KeyStatsSnapshot: Codable, Sendable {
    let available: Bool
    let keyPresses: Int
    let leftClicks: Int
    let rightClicks: Int
    let otherClicks: Int
    let mouseDistanceMeters: Double
    let scrollDistancePixels: Double
    let peakKPS: Int
    let peakCPS: Int

    var totalClicks: Int {
        leftClicks + rightClicks + otherClicks
    }

    static let unavailable = KeyStatsSnapshot(
        available: false, keyPresses: 0, leftClicks: 0, rightClicks: 0,
        otherClicks: 0, mouseDistanceMeters: 0, scrollDistancePixels: 0,
        peakKPS: 0, peakCPS: 0)

    static let demo = KeyStatsSnapshot(
        available: true, keyPresses: 18_642, leftClicks: 3_281,
        rightClicks: 246, otherClicks: 92, mouseDistanceMeters: 1_284,
        scrollDistancePixels: 486_200, peakKPS: 12, peakCPS: 7)
}

/// Subset of debugtheworldbot/keyStats' DailyStats Codable payload.
/// Unknown fields such as per-key and per-app breakdowns are intentionally
/// ignored; MacTR only reads aggregate values for the LCD.
private struct ExternalKeyStatsDailyStats: Decodable {
    let date: Date
    let keyPresses: Int
    let leftClicks: Int
    let rightClicks: Int
    let middleClicks: Int
    let sideBackClicks: Int
    let sideForwardClicks: Int
    let mouseDistance: Double
    let scrollDistance: Double
    let peakKPS: Int
    let peakCPS: Int

    enum CodingKeys: String, CodingKey {
        case date
        case keyPresses
        case leftClicks
        case rightClicks
        case middleClicks
        case sideBackClicks
        case sideForwardClicks
        case otherClicks
        case mouseDistance
        case scrollDistance
        case peakKPS
        case peakCPS
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        date = try values.decodeIfPresent(Date.self, forKey: .date) ?? .distantPast
        keyPresses = try values.decodeIfPresent(
            Int.self, forKey: .keyPresses) ?? 0
        leftClicks = try values.decodeIfPresent(
            Int.self, forKey: .leftClicks) ?? 0
        rightClicks = try values.decodeIfPresent(
            Int.self, forKey: .rightClicks) ?? 0
        middleClicks = try values.decodeIfPresent(
            Int.self, forKey: .middleClicks) ?? 0
        let legacyOther = try values.decodeIfPresent(
            Int.self, forKey: .otherClicks) ?? 0
        sideBackClicks = try values.decodeIfPresent(
            Int.self, forKey: .sideBackClicks) ?? legacyOther
        sideForwardClicks = try values.decodeIfPresent(
            Int.self, forKey: .sideForwardClicks) ?? 0
        mouseDistance = try values.decodeIfPresent(
            Double.self, forKey: .mouseDistance) ?? 0
        scrollDistance = try values.decodeIfPresent(
            Double.self, forKey: .scrollDistance) ?? 0
        peakKPS = Self.decodeIntOrDouble(values, key: .peakKPS)
        peakCPS = Self.decodeIntOrDouble(values, key: .peakCPS)
    }

    private static func decodeIntOrDouble(
        _ values: KeyedDecodingContainer<CodingKeys>, key: CodingKeys
    ) -> Int {
        if let value = try? values.decodeIfPresent(Int.self, forKey: key) {
            return value
        }
        if let value = try? values.decodeIfPresent(Double.self, forKey: key) {
            return Int(value)
        }
        return 0
    }
}

/// Reads aggregate statistics generated by the standalone keyStats app.
/// MacTR no longer installs its own global event tap or records duplicate data.
final class KeyStatsCollector: @unchecked Sendable {
    private let appID = "com.keystats.app" as CFString
    private let statsKey = "dailyStats" as CFString
    private let calibrationKey = "mouseDistanceCalibrationFactor" as CFString
    private let baseMetersPerPixel = 0.000264583

    func start(requestPermission: Bool) {
        // keyStats owns Input Monitoring permission and event collection.
    }

    func stop() {
        // No resources are owned by MacTR.
    }

    func collect() -> KeyStatsSnapshot {
        CFPreferencesAppSynchronize(appID)
        guard let value = CFPreferencesCopyAppValue(statsKey, appID),
              let data = value as? Data,
              let stats = try? JSONDecoder().decode(
                ExternalKeyStatsDailyStats.self, from: data)
        else {
            return .unavailable
        }

        let isToday = Calendar.current.isDateInToday(stats.date)
        let calibration = calibrationFactor()
        let otherClicks = stats.middleClicks
            + stats.sideBackClicks + stats.sideForwardClicks

        return KeyStatsSnapshot(
            available: true,
            keyPresses: isToday ? stats.keyPresses : 0,
            leftClicks: isToday ? stats.leftClicks : 0,
            rightClicks: isToday ? stats.rightClicks : 0,
            otherClicks: isToday ? otherClicks : 0,
            mouseDistanceMeters:
                isToday
                    ? stats.mouseDistance * baseMetersPerPixel * calibration
                    : 0,
            scrollDistancePixels: isToday ? stats.scrollDistance : 0,
            peakKPS: isToday ? stats.peakKPS : 0,
            peakCPS: isToday ? stats.peakCPS : 0)
    }

    private func calibrationFactor() -> Double {
        guard let value = CFPreferencesCopyAppValue(calibrationKey, appID)
        else { return 1 }
        if let number = value as? NSNumber {
            return max(0.01, number.doubleValue)
        }
        return 1
    }
}
